/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedChartsRouteImport } from './routes/_authenticated/charts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKosherRouteImport } from './routes/_authenticated/kosher'
import { Route as AuthenticatedManagerDashboardRouteImport } from './routes/_authenticated/manager-dashboard'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSystemsIdRouteImport } from './routes/_authenticated/systems.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicWeeklyCrmReportRouteImport } from './routes/api/public/weekly-crm-report'
import { Route as AuthenticatedCCrmIndexRouteImport } from './routes/_authenticated/c.$crm.index'
import { Route as AuthenticatedCCrmIdRouteImport } from './routes/_authenticated/c.$crm.$id'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'
import { Route as ApiPublicHooksInboundEmailRouteImport } from './routes/api/public/hooks/inbound-email'
import { Route as ApiPublicHooksProcessVoiceQueueRouteImport } from './routes/api/public/hooks/process-voice-queue'
import { Route as ApiPublicHooksScheduledBackupCheckRouteImport } from './routes/api/public/hooks/scheduled-backup-check'
import { Route as ApiPublicHooksWeeklyBackupRouteImport } from './routes/api/public/hooks/weekly-backup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChartsRoute = AuthenticatedChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKosherRoute = AuthenticatedKosherRouteImport.update({
  id: '/kosher',
  path: '/kosher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerDashboardRoute =
  AuthenticatedManagerDashboardRouteImport.update({
    id: '/manager-dashboard',
    path: '/manager-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemsIdRoute = AuthenticatedSystemsIdRouteImport.update({
  id: '/systems/$id',
  path: '/systems/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeeklyCrmReportRoute =
  ApiPublicWeeklyCrmReportRouteImport.update({
    id: '/api/public/weekly-crm-report',
    path: '/api/public/weekly-crm-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCCrmIndexRoute = AuthenticatedCCrmIndexRouteImport.update({
  id: '/c/$crm/',
  path: '/c/$crm/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCCrmIdRoute = AuthenticatedCCrmIdRouteImport.update({
  id: '/c/$crm/$id',
  path: '/c/$crm/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInboundEmailRoute =
  ApiPublicHooksInboundEmailRouteImport.update({
    id: '/api/public/hooks/inbound-email',
    path: '/api/public/hooks/inbound-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessVoiceQueueRoute =
  ApiPublicHooksProcessVoiceQueueRouteImport.update({
    id: '/api/public/hooks/process-voice-queue',
    path: '/api/public/hooks/process-voice-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScheduledBackupCheckRoute =
  ApiPublicHooksScheduledBackupCheckRouteImport.update({
    id: '/api/public/hooks/scheduled-backup-check',
    path: '/api/public/hooks/scheduled-backup-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyBackupRoute =
  ApiPublicHooksWeeklyBackupRouteImport.update({
    id: '/api/public/hooks/weekly-backup',
    path: '/api/public/hooks/weekly-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kosher': typeof AuthenticatedKosherRoute
  '/manager-dashboard': typeof AuthenticatedManagerDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/systems/$id': typeof AuthenticatedSystemsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/weekly-crm-report': typeof ApiPublicWeeklyCrmReportRoute
  '/c/$crm/$id': typeof AuthenticatedCCrmIdRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/inbound-email': typeof ApiPublicHooksInboundEmailRoute
  '/api/public/hooks/process-voice-queue': typeof ApiPublicHooksProcessVoiceQueueRoute
  '/api/public/hooks/scheduled-backup-check': typeof ApiPublicHooksScheduledBackupCheckRoute
  '/api/public/hooks/weekly-backup': typeof ApiPublicHooksWeeklyBackupRoute
  '/c/$crm/': typeof AuthenticatedCCrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kosher': typeof AuthenticatedKosherRoute
  '/manager-dashboard': typeof AuthenticatedManagerDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/systems/$id': typeof AuthenticatedSystemsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/weekly-crm-report': typeof ApiPublicWeeklyCrmReportRoute
  '/c/$crm/$id': typeof AuthenticatedCCrmIdRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/inbound-email': typeof ApiPublicHooksInboundEmailRoute
  '/api/public/hooks/process-voice-queue': typeof ApiPublicHooksProcessVoiceQueueRoute
  '/api/public/hooks/scheduled-backup-check': typeof ApiPublicHooksScheduledBackupCheckRoute
  '/api/public/hooks/weekly-backup': typeof ApiPublicHooksWeeklyBackupRoute
  '/c/$crm': typeof AuthenticatedCCrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/charts': typeof AuthenticatedChartsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kosher': typeof AuthenticatedKosherRoute
  '/_authenticated/manager-dashboard': typeof AuthenticatedManagerDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/systems/$id': typeof AuthenticatedSystemsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/weekly-crm-report': typeof ApiPublicWeeklyCrmReportRoute
  '/_authenticated/c/$crm/$id': typeof AuthenticatedCCrmIdRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/inbound-email': typeof ApiPublicHooksInboundEmailRoute
  '/api/public/hooks/process-voice-queue': typeof ApiPublicHooksProcessVoiceQueueRoute
  '/api/public/hooks/scheduled-backup-check': typeof ApiPublicHooksScheduledBackupCheckRoute
  '/api/public/hooks/weekly-backup': typeof ApiPublicHooksWeeklyBackupRoute
  '/_authenticated/c/$crm/': typeof AuthenticatedCCrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/audit'
    | '/backups'
    | '/charts'
    | '/dashboard'
    | '/kosher'
    | '/manager-dashboard'
    | '/reports'
    | '/systems/$id'
    | '/api/public/health'
    | '/api/public/weekly-crm-report'
    | '/c/$crm/$id'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/inbound-email'
    | '/api/public/hooks/process-voice-queue'
    | '/api/public/hooks/scheduled-backup-check'
    | '/api/public/hooks/weekly-backup'
    | '/c/$crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/audit'
    | '/backups'
    | '/charts'
    | '/dashboard'
    | '/kosher'
    | '/manager-dashboard'
    | '/reports'
    | '/systems/$id'
    | '/api/public/health'
    | '/api/public/weekly-crm-report'
    | '/c/$crm/$id'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/inbound-email'
    | '/api/public/hooks/process-voice-queue'
    | '/api/public/hooks/scheduled-backup-check'
    | '/api/public/hooks/weekly-backup'
    | '/c/$crm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/audit'
    | '/_authenticated/backups'
    | '/_authenticated/charts'
    | '/_authenticated/dashboard'
    | '/_authenticated/kosher'
    | '/_authenticated/manager-dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/systems/$id'
    | '/api/public/health'
    | '/api/public/weekly-crm-report'
    | '/_authenticated/c/$crm/$id'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/inbound-email'
    | '/api/public/hooks/process-voice-queue'
    | '/api/public/hooks/scheduled-backup-check'
    | '/api/public/hooks/weekly-backup'
    | '/_authenticated/c/$crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicWeeklyCrmReportRoute: typeof ApiPublicWeeklyCrmReportRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
  ApiPublicHooksInboundEmailRoute: typeof ApiPublicHooksInboundEmailRoute
  ApiPublicHooksProcessVoiceQueueRoute: typeof ApiPublicHooksProcessVoiceQueueRoute
  ApiPublicHooksScheduledBackupCheckRoute: typeof ApiPublicHooksScheduledBackupCheckRoute
  ApiPublicHooksWeeklyBackupRoute: typeof ApiPublicHooksWeeklyBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charts': {
      id: '/_authenticated/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AuthenticatedChartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kosher': {
      id: '/_authenticated/kosher'
      path: '/kosher'
      fullPath: '/kosher'
      preLoaderRoute: typeof AuthenticatedKosherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager-dashboard': {
      id: '/_authenticated/manager-dashboard'
      path: '/manager-dashboard'
      fullPath: '/manager-dashboard'
      preLoaderRoute: typeof AuthenticatedManagerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/systems/$id': {
      id: '/_authenticated/systems/$id'
      path: '/systems/$id'
      fullPath: '/systems/$id'
      preLoaderRoute: typeof AuthenticatedSystemsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weekly-crm-report': {
      id: '/api/public/weekly-crm-report'
      path: '/api/public/weekly-crm-report'
      fullPath: '/api/public/weekly-crm-report'
      preLoaderRoute: typeof ApiPublicWeeklyCrmReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$crm/': {
      id: '/_authenticated/c/$crm/'
      path: '/c/$crm'
      fullPath: '/c/$crm/'
      preLoaderRoute: typeof AuthenticatedCCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$crm/$id': {
      id: '/_authenticated/c/$crm/$id'
      path: '/c/$crm/$id'
      fullPath: '/c/$crm/$id'
      preLoaderRoute: typeof AuthenticatedCCrmIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/inbound-email': {
      id: '/api/public/hooks/inbound-email'
      path: '/api/public/hooks/inbound-email'
      fullPath: '/api/public/hooks/inbound-email'
      preLoaderRoute: typeof ApiPublicHooksInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-voice-queue': {
      id: '/api/public/hooks/process-voice-queue'
      path: '/api/public/hooks/process-voice-queue'
      fullPath: '/api/public/hooks/process-voice-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessVoiceQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scheduled-backup-check': {
      id: '/api/public/hooks/scheduled-backup-check'
      path: '/api/public/hooks/scheduled-backup-check'
      fullPath: '/api/public/hooks/scheduled-backup-check'
      preLoaderRoute: typeof ApiPublicHooksScheduledBackupCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-backup': {
      id: '/api/public/hooks/weekly-backup'
      path: '/api/public/hooks/weekly-backup'
      fullPath: '/api/public/hooks/weekly-backup'
      preLoaderRoute: typeof ApiPublicHooksWeeklyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedChartsRoute: typeof AuthenticatedChartsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKosherRoute: typeof AuthenticatedKosherRoute
  AuthenticatedManagerDashboardRoute: typeof AuthenticatedManagerDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSystemsIdRoute: typeof AuthenticatedSystemsIdRoute
  AuthenticatedCCrmIdRoute: typeof AuthenticatedCCrmIdRoute
  AuthenticatedCCrmIndexRoute: typeof AuthenticatedCCrmIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedChartsRoute: AuthenticatedChartsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKosherRoute: AuthenticatedKosherRoute,
  AuthenticatedManagerDashboardRoute: AuthenticatedManagerDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSystemsIdRoute: AuthenticatedSystemsIdRoute,
  AuthenticatedCCrmIdRoute: AuthenticatedCCrmIdRoute,
  AuthenticatedCCrmIndexRoute: AuthenticatedCCrmIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicWeeklyCrmReportRoute: ApiPublicWeeklyCrmReportRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
  ApiPublicHooksInboundEmailRoute: ApiPublicHooksInboundEmailRoute,
  ApiPublicHooksProcessVoiceQueueRoute: ApiPublicHooksProcessVoiceQueueRoute,
  ApiPublicHooksScheduledBackupCheckRoute:
    ApiPublicHooksScheduledBackupCheckRoute,
  ApiPublicHooksWeeklyBackupRoute: ApiPublicHooksWeeklyBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
