/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChartsRouteImport } from './routes/_authenticated/charts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicWeeklyCrmReportRouteImport } from './routes/api/public/weekly-crm-report'
import { Route as AuthenticatedSystemsIdRouteImport } from './routes/_authenticated/systems.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChartsRoute = AuthenticatedChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWeeklyCrmReportRoute =
  ApiPublicWeeklyCrmReportRouteImport.update({
    id: '/api/public/weekly-crm-report',
    path: '/api/public/weekly-crm-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSystemsIdRoute = AuthenticatedSystemsIdRouteImport.update({
  id: '/systems/$id',
  path: '/systems/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/systems/$id': typeof AuthenticatedSystemsIdRoute
  '/api/public/weekly-crm-report': typeof ApiPublicWeeklyCrmReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/systems/$id': typeof AuthenticatedSystemsIdRoute
  '/api/public/weekly-crm-report': typeof ApiPublicWeeklyCrmReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/charts': typeof AuthenticatedChartsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/systems/$id': typeof AuthenticatedSystemsIdRoute
  '/api/public/weekly-crm-report': typeof ApiPublicWeeklyCrmReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/charts'
    | '/dashboard'
    | '/systems/$id'
    | '/api/public/weekly-crm-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/charts'
    | '/dashboard'
    | '/systems/$id'
    | '/api/public/weekly-crm-report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/charts'
    | '/_authenticated/dashboard'
    | '/_authenticated/systems/$id'
    | '/api/public/weekly-crm-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWeeklyCrmReportRoute: typeof ApiPublicWeeklyCrmReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charts': {
      id: '/_authenticated/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AuthenticatedChartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/weekly-crm-report': {
      id: '/api/public/weekly-crm-report'
      path: '/api/public/weekly-crm-report'
      fullPath: '/api/public/weekly-crm-report'
      preLoaderRoute: typeof ApiPublicWeeklyCrmReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/systems/$id': {
      id: '/_authenticated/systems/$id'
      path: '/systems/$id'
      fullPath: '/systems/$id'
      preLoaderRoute: typeof AuthenticatedSystemsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChartsRoute: typeof AuthenticatedChartsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSystemsIdRoute: typeof AuthenticatedSystemsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChartsRoute: AuthenticatedChartsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSystemsIdRoute: AuthenticatedSystemsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWeeklyCrmReportRoute: ApiPublicWeeklyCrmReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
